# Generated by Django 5.1.7 on 2025-08-22 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataTarefa', models.DateField()),
                ('LocalTarefa', models.CharField(max_length=64)),
                ('descricaoTarefa', models.CharField(max_length=1000)),
                ('tarefa', models.CharField(max_length=64)),
                ('objetivoTarefa', models.CharField(max_length=250)),
                ('autorTarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareafas_por_autor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
