# Generated by Django 5.1.7 on 2025-08-28 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0002_curtidas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Curtidas',
        ),
    ]
