# Generated by Django 5.1.7 on 2025-08-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('td', '0003_tarefas_curtidas_delete_curtidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='curtidas',
        ),
    ]
